baseURL = 'https://janbanana.github.io/minmat/'
languageCode = 'en-us'
title = 'Minmat'
theme = 'plague'

[params]
  siteHeaderText = "Minmat"
  siteFooterText = "Powered by [Hugo](https://gohugo.io/) and the [plague](https://github.com/brianreumere/plague) theme."
  colors = "default"

  [params.hcard]
    fullName = "Jan"
